services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kritiscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
volumes:
  db:
networks:
  db:
    driver: bridge








